language: cpp
compiler:
    - g++
dist: trusty
sudo: required

addons:
    apt:
        sources:
        packages:
            - build-essential
            - cmake
            - cmake-data
            - lcov
            - zlib1g-dev
install:
    - mkdir build && cd build

    - wget -O libzip.tar.gz http://www.nih.at/libzip/libzip-1.2.0.tar.gz
    - tar -zxvf libzip.tar.gz && cd libzip-1.2.0
    - cmake . && make && sudo make install
    - sudo cp zipconf.h /usr/local/include && cd ..

    - wget -O unrar.tar.gz http://www.rarlab.com/rar/unrarsrc-5.5.6.tar.gz
    - tar -zxvf unrar.tar.gz && cd unrar
    - make lib && sudo make install-lib
    - sudo mkdir /usr/local/include/unrar && sudo cp dll.hpp /usr/local/include/unrar && cd ..
script:
    - cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=ON ..
    - make
    - make archivepp_coverage

after_success:
    - bash <(curl -s https://codecov.io/bash)
